### PR TITLE
Updates difference-deep-and-normal-learning.md

### PR DESCRIPTION
**Pull request by shashankgroovy**
Fixes to grammatical errors

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks!

**Comment by shashankgroovy** [comment]
Hey! @rasbt thanks for merging the PR.
Also I'd love to contribute at other places in the book as well if you have anymore tedious tasks like these, reviewing or anything else, feel free to redirect them at me. I think it'd be a good exposure for me as I have just started with Machine Learning. Thanks!

**Comment by rasbt** [comment]
No problem, I am the one who has to say thanks :). Contributions to the book itself are a bit tricky since I cannot really make changes to the contents (anymore); that's up to the publisher, really, and they said that they are not going to make any changes to it :(. Maybe, there will be a second version one day where I'd add some additional sections and chapters, but that's really far down the road. 
So, for the same reason, I wouldn't want to alter the code notebooks since they'd be inconsistent with the book content otherwise ...

However, I am just thinking about other ways to contribute ... Of course, I'd welcome any fixes and/or suggestions regarding the FAQ or "bonus" notebooks. Or something like a directory with "user experiences or applications" could be interesting. Maybe examples from the book applied to different datasets or so? Also, I'd welcome any other "bonus" code notebooks or write-ups on material that I may have not covered in the book, or things that were explained not explained very well. So, if you are up to it, I'd really welcome something like that, but please don't see it as a commitment ... just feel free to open issues and pull requests if you like to add something and we could discuss it further :). Thanks!

**Comment by shashankgroovy** [comment]
That sounds wonderful :). I think I'll begin initially with the FAQs. And as I progress around the book and Machine Learning in general, whenever I will come up with any write-ups or with use-cases/application to support or add in the book then we could discuss it further in the future :)

**Pull request merged**
